
import bpy
import math

# ==========================================================
# === This script was auto-generated by your LCA tool ===
# === Model: Building-A
# ==========================================================

# --- Parameters (Injected from your script) ---
L = 48.0
W = 12.0
H_STORY = 3.0
N_STORIES = 4
TOTAL_H = 12.0

NUM_COLS_X = 9
NUM_COLS_Y = 3
X_SPACING = 6.0
Y_SPACING = 6.0
X_START = -24.0
Y_START = -6.0

WWR_N = 0.5
WWR_S = 0.25
WWR_E = 0.0
WWR_W = 0.0

N_CORES = 1

# --- Cosmetic Parameters ---
SLAB_THICKNESS = 0.3
WALL_THICKNESS = 0.3
COL_RADIUS = 0.25
BEAM_HEIGHT = 0.4
BEAM_WIDTH = 0.3
CORE_DIM = 5.0
    
# --- Helper Functions ---

def clear_scene():
    # Clear all mesh objects from the scene.
    bpy.ops.object.select_all(action='DESELECT')
    bpy.ops.object.select_by_type(type='MESH')
    bpy.ops.object.delete()
    
    # Delete collections
    for collection in bpy.data.collections:
        if not collection.name == "Scene Collection":
            bpy.data.collections.remove(collection)

def create_collection(name):
    # Create a new collection and link it to the scene.
    if name in bpy.data.collections:
        return bpy.data.collections[name]
    new_coll = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(new_coll)
    return new_coll

def add_to_collection(obj, coll):
    # Move an object to a collection.
    # Unlink from all other collections
    for c in obj.users_collection:
        c.objects.unlink(obj)
    # Link to the new collection
    coll.objects.link(obj)

def create_box(name, location, dimensions, coll):
    # Helper to create a simple box.
    bpy.ops.mesh.primitive_cube_add(size=1, location=location, enter_editmode=False)
    obj = bpy.context.active_object
    obj.name = name
    obj.dimensions = dimensions
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    add_to_collection(obj, coll)
    return obj

def create_cylinder(name, location, radius, depth, coll):
    # Helper to create a simple cylinder.
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, 
        depth=depth, 
        location=location,
        vertices=16
    )
    obj = bpy.context.active_object
    obj.name = name
    add_to_collection(obj, coll)
    return obj

def apply_boolean(target, cutter, operation='DIFFERENCE'):
    # Apply a boolean modifier.
    mod = target.modifiers.new(name=f"Bool_{cutter.name}", type='BOOLEAN')
    mod.object = cutter
    mod.operation = operation
    cutter.display_type = 'WIRE' # Make cutter visible but non-intrusive
    cutter.hide_render = True
    return mod

# --- Main Script ---

def build_model():
    print("Building parametric model in Blender...")
    
    # --- 1. Setup Collections ---
    coll_slabs = create_collection("Slabs")
    coll_cols = create_collection("Columns")
    coll_beams = create_collection("Beams")
    coll_facades = create_collection("Facades")
    coll_cores = create_collection("Cores")
    coll_cutters = create_collection("Cutters (Hide Me)")

    # --- 2. Create Slabs ---
    # Loop N_STORIES + 1 to include ground floor and roof
    for i in range(N_STORIES + 1):
        z_pos = i * H_STORY
        # Center slab at (0, 0, z_pos)
        loc = (0, 0, z_pos - (SLAB_THICKNESS / 2.0))
        if i == 0:
            name = "Ground_Slab"
        elif i == N_STORIES:
            name = "Roof_Slab"
        else:
            name = f"Slab_L{i}"
        
        create_box(name, loc, (L, W, SLAB_THICKNESS), coll_slabs)

    # --- 3. Create Columns ---
    if NUM_COLS_X > 0 and NUM_COLS_Y > 0:
        for i in range(NUM_COLS_X):
            x = X_START + i * X_SPACING
            for j in range(NUM_COLS_Y):
                y = Y_START + j * Y_SPACING
                loc = (x, y, TOTAL_H / 2.0) # Center of the column
                name = f"Column_{i}_{j}"
                create_cylinder(name, loc, COL_RADIUS, TOTAL_H, coll_cols)

    # --- 4. Create Beams ---
    # Beams sit *under* the slabs (except ground floor)
    for k in range(N_STORIES):
        level = k + 1
        z_pos = (level * H_STORY) - SLAB_THICKNESS - (BEAM_HEIGHT / 2.0)
        
        # Beams along X-axis
        if NUM_COLS_Y > 0:
            for j in range(NUM_COLS_Y):
                y = Y_START + j * Y_SPACING
                loc = (0, y, z_pos)
                name = f"Beam_X_L{level}_{j}"
                create_box(name, loc, (L, BEAM_WIDTH, BEAM_HEIGHT), coll_beams)

        # Beams along Y-axis
        if NUM_COLS_X > 0:
            for i in range(NUM_COLS_X):
                x = X_START + i * X_SPACING
                loc = (x, 0, z_pos)
                name = f"Beam_Y_L{level}_{i}"
                create_box(name, loc, (BEAM_WIDTH, W, BEAM_HEIGHT), coll_beams)

    # --- 5. Create Facades (Walls and Windows) per Story ---
    
    # Loop for each story, from ground floor up
    for i in range(N_STORIES):
        # Calculate vertical position for this story's walls
        # Wall starts on top of slab (z = i * H_STORY)
        # Wall stops at bottom of beams for the *next* level up
        # (z = (i+1) * H_STORY - SLAB_THICKNESS - BEAM_HEIGHT)
        
        z_bottom = i * H_STORY
        z_top = (i + 1) * H_STORY - SLAB_THICKNESS - BEAM_HEIGHT
        
        # Ensure parameters are valid (e.g., story height > slab + beam)
        panel_height = z_top - z_bottom
        if panel_height <= 0:
            print(f"Skipping wall generation for level {i}, panel height is zero or negative.")
            continue
            
        # Z-location for the new centered wall panel
        z_center = z_bottom + (panel_height / 2.0)

        # Create the 4 wall panels for this story
        wall_n = create_box(f"Wall_North_L{i}", (0, W/2, z_center), (L, WALL_THICKNESS, panel_height), coll_facades)
        wall_s = create_box(f"Wall_South_L{i}", (0, -W/2, z_center), (L, WALL_THICKNESS, panel_height), coll_facades)
        wall_e = create_box(f"Wall_East_L{i}", (L/2, 0, z_center), (WALL_THICKNESS, W, panel_height), coll_facades)
        wall_w = create_box(f"Wall_West_L{i}", (-L/2, 0, z_center), (WALL_THICKNESS, W, panel_height), coll_facades)

        # --- Tweak 2: Create window cutouts per-bay ---
        
        # Define a "cosmetic" window height, e.g., 80% of the panel height
        window_height = panel_height * 0.8
        window_z_pos = z_center # Windows are vertically centered in the panel
        
        # North/South Facades (distributed along X-axis)
        bay_width_x = X_SPACING
        if bay_width_x > 0 and (NUM_COLS_X - 1) > 0:
            # North Windows
            if WWR_N > 0:
                # Use math.sqrt(WWR) to get a 1D ratio for the width
                window_width = bay_width_x * math.sqrt(WWR_N)
                window_width = min(window_width, bay_width_x * 0.9) # Add 10% margin
                
                for j in range(NUM_COLS_X - 1):
                    bay_center_x = (X_START + j * X_SPACING) + (bay_width_x / 2.0)
                    loc_n = (bay_center_x, W/2, window_z_pos)
                    cutter_n = create_box(f"Cutter_N_L{i}_B{j}", loc_n, (window_width, WALL_THICKNESS*2, window_height), coll_cutters)
                    apply_boolean(wall_n, cutter_n)

            # South Windows
            if WWR_S > 0:
                window_width = bay_width_x * math.sqrt(WWR_S)
                window_width = min(window_width, bay_width_x * 0.9)
                
                for j in range(NUM_COLS_X - 1):
                    bay_center_x = (X_START + j * X_SPACING) + (bay_width_x / 2.0)
                    loc_s = (bay_center_x, -W/2, window_z_pos)
                    cutter_s = create_box(f"Cutter_S_L{i}_B{j}", loc_s, (window_width, WALL_THICKNESS*2, window_height), coll_cutters)
                    apply_boolean(wall_s, cutter_s)

        # East/West Facades (distributed along Y-axis)
        bay_width_y = Y_SPACING
        if bay_width_y > 0 and (NUM_COLS_Y - 1) > 0:
            # East Windows
            if WWR_E > 0:
                window_width = bay_width_y * math.sqrt(WWR_E)
                window_width = min(window_width, bay_width_y * 0.9)

                for j in range(NUM_COLS_Y - 1):
                    bay_center_y = (Y_START + j * Y_SPACING) + (bay_width_y / 2.0)
                    loc_e = (L/2, bay_center_y, window_z_pos)
                    cutter_e = create_box(f"Cutter_E_L{i}_B{j}", loc_e, (WALL_THICKNESS*2, window_width, window_height), coll_cutters)
                    apply_boolean(wall_e, cutter_e)

            # West Windows
            if WWR_W > 0:
                window_width = bay_width_y * math.sqrt(WWR_W)
                window_width = min(window_width, bay_width_y * 0.9)

                for j in range(NUM_COLS_Y - 1):
                    bay_center_y = (Y_START + j * Y_SPACING) + (bay_width_y / 2.0)
                    loc_w = (-L/2, bay_center_y, window_z_pos)
                    cutter_w = create_box(f"Cutter_W_L{i}_B{j}", loc_w, (WALL_THICKNESS*2, window_width, window_height), coll_cutters)
                    apply_boolean(wall_w, cutter_w)

    # --- 6. Create Vertical Cores ---
    # Center the cores along the X-axis and place them adjacent to the North wall.
    
    # Calculate the total span of all cores (including 1m spacing)
    if N_CORES > 0:
        total_core_span = (N_CORES * CORE_DIM) + (N_CORES - 1) * 1.0
        
        # Calculate the X-coordinate for the center of the *first* core
        # This centers the whole block of cores at X=0
        current_core_x = -total_core_span / 2.0 + (CORE_DIM / 2.0)
        
        # Calculate the Y-coordinate, adjacent to the *inside* of the North wall
        # North wall is at +W/2. Its inner face is at (W/2) - WALL_THICKNESS
        # The core's center will be half its dimension south of that.
        core_y = (W / 2.0) - WALL_THICKNESS - (CORE_DIM / 2.0)
        
        for i in range(N_CORES):
            loc = (current_core_x, core_y, TOTAL_H / 2.0)
            name = f"Core_{i+1}"
            create_box(name, loc, (CORE_DIM, CORE_DIM, TOTAL_H), coll_cores)
            
            # Move the X-coordinate for the next core
            current_core_x += CORE_DIM + 1.0

    print("Blender model generation complete.")


# --- Run the script ---
clear_scene()
build_model()
bpy.ops.object.select_all(action='DESELECT')

